### ISSUE TITLE
Define promotion type and fields

### ISSUE THREAD

**Issue by kk3039** [CSCI-GA-2820-SP23-003/promotions#11]
**As a** promotion manager
**I need** to know what kinds of promotions can be provided to customers
**So that** I can design and add promotions
   
 ### Details and Assumptions
This ticket is mainly for us as a team to agree on what type of promotions to support. We need to consider three parts:
- which product(s)/ sitewide
- discount amount (% and/or $ off)
- timeframe

See discussions in the comments [here](https://github.com/CSCI-GA-2820-SP23-003/promotions/issues/6)

In real life, this is a business requirement and the development team needs to design based on the requirements.

 ### Acceptance Criteria  
 Since this ticket is usually a business requirement, the Gherkin template does not apply here. There is no code to test.

**Comment by Po-Y-H** [comment]
1. Promo name
2. Promo id
3. Start date
4. Promo type
5. Promo value
6. Promo active
7. Promo expiration

**Comment by snehil585** [comment]
Promotion Types :
1. Percentage Discount on Final Price.
2. Seasonal Discount
3. Clearance Sale
4. Buy one and get one
5. Amount Discount

**Comment by Po-Y-H** [comment]
> Promotion Types :
> 
> 1. Percentage Discount on Final Price.
> 2. Seasonal Discount
> 3. Clearance Sale
> 4. Buy one and get one
> 5. Amount Discount

Promo type:
We first use 1. and 4. mentioned in Doc of Squad Assignments.
"buy 1 get 1 free", 
"20% off"

**Comment by harshitakukreja** [comment]
As discussed in lecture 5, this might be used in Sprint 2
