### ISSUE TITLE
Search always returns the first query 

### ISSUE THREAD

**Issue by soowhan-park** [CSCI-GA-2820-SP23-003/promotions#113]
**Describe the bug**
Searching for query always returns the first item. For example, when I type "Promo2" in the "Title" field and click the "Search" button, it returns the "Promo1" instead of "Promo2" 

**To Reproduce**
1. Go to our URL Port after `honcho start`
2. Run `behave` in another terminal 
3. Type "Promo2" in the "Title" field and click "Search" button
4. See the error --- the first item in the query is always returned

**Expected behavior**
All the related data associated with "Promo2" should be displayed 

**Observed behavior**
Our search always returns the data associated with "Promo1"

**Comment by harshitakukreja** [comment]
@soowhan-park this has been merged into master by @snehil585 but I see that BDD tests are not passing.
