### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Po-Y-H** [CSCI-GA-2820-SP23-003/promotions#127]
**As a** Developer
**I need** display the detailed information about Promo service
**So that** everyone will know how to use the Promo service
   
 ### Details and Assumptions
 README.md should include the following information:

1. The dev link and prod link
2. list of  query route
3. The setup instruction
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by harshitakukreja** [comment]
[Uploading... Screenshot 2023-05-03 at 5.02.22 PM.png]
