### ISSUE TITLE
Update the routes.py file to contain the Flask service routes for Promotions

### ISSUE THREAD

**Issue by harshitakukreja** [CSCI-GA-2820-SP23-003/promotions#15]
**As a** Developer
**I need** to update the routes.py file to contain the Flask Service routes of Promotions
**So that** I am able to work with the Promotions object to provide the required service operations.
   
 ### Details and Assumptions
 * Starter code for initialization is already written in the routes.py file
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given routes.py is updated
 When routes are invoked using APIs
 Then operations can be performed without errors
```

**Comment by harshitakukreja** [comment]
@snehil585 we should close this issue, as the professor mentioned in the last lecture while reviewing our board that this is something we do for every service and is not independently required to be a user story.

**Comment by snehil585** [comment]
Oh sure. I have moved it to closed section.

Thanks
Snehil


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/06/23,
08:40:56 PM
