### ISSUE TITLE
Design database model for Promotions

### ISSUE THREAD

**Issue by harshitakukreja** [CSCI-GA-2820-SP23-003/promotions#17]
**As a** Developer
**I need** to design a database model for the Promotions service
**So that** I can perform CRUD plus List operations on the Promotions service
   
 ### Details and Assumptions
 * We know the tables and required fields beforehand
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I run the application
 When any of the operations are performed
 Then related information is retrieved from or stored in the database
```

**Comment by soowhan-park** [comment]
Database Design for Promotion (Version 1) 

Table 1: Time Period 
t_id (primary key), Int, id of time stamp
start_date, TIMESTAMP, Start date of promotion
end_date, TIMESTAMP, End date of promotion 


Table 2: Product 
p_id (primary key), int, id of product 
name, varchar, Name of product
price, int, Price of product 
promo_history, bool, True if the product was on promotion in the past

Table 3: Discount 
d_id (primary key), int, id of discount
promo_type, varchar, type of promotion
promo_amount, int, Amount of promotion discount (All site $ off) -> temporary
p_id (foreign key), int, foreign key referencing product id 
t_id (foreign key), int, foreign key referencing time period id

**Comment by kk3039** [comment]
We should reopen this user story, because the tests for serialization and deserialization are not completed yet.

**Comment by soowhan-park** [comment]
I will create another user story for the serialization/deserialization tests

**Comment by harshitakukreja** [comment]
Hey, a gentle reminder that we were asked not to make stories for tests. We could either rename it or open the issue back again.

**Comment by soowhan-park** [comment]
Oh thanks for the reminder!
