### ISSUE TITLE
Create database for Promotions

### ISSUE THREAD

**Issue by harshitakukreja** [CSCI-GA-2820-SP23-003/promotions#18]
**As a** Developer
**I need** to create database model for the Promotions service
**So that** I can perform CRUD plus List operations on the Promotions service
   
 ### Details and Assumptions
 * We use PostgreSQL for our database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I run the application
 When any of the operations are performed
 Then related information is retrieved from or stored in the database
```

**Comment by soowhan-park** [comment]
Can you guys review my PR for db in models.py? 

Thanks!

**Comment by harshitakukreja** [comment]
Raised ([#29](https://github.com/CSCI-GA-2820-SP23-003/promotions/issues/29)) along with a PR ([#30](https://github.com/CSCI-GA-2820-SP23-003/promotions/pull/30)) correcting it.

**Comment by harshitakukreja** [comment]
Raised a PR ([#31](https://github.com/CSCI-GA-2820-SP23-003/promotions/pull/31)) to add factories.py in tests for db init.
Can you review it @soowhan-park, I've added you as the reviewer?
