### ISSUE TITLE
Ability to read promotions 

### ISSUE THREAD

**Issue by soowhan-park** [CSCI-GA-2820-SP23-003/promotions#19]
**As a** Promotion Team Member / Manager
**I need** the ability to read a promotion 
**So that** I can check the details of the promotion
   
 ### Details and Assumptions
 The following information will be returned from API:
- Product id (int) 
- User id (int)  
- Promotion type (str? TBD) 
- Promotion status (bool) -> true if promotion is active
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I read the details of the promotion
 Then the information above should be returned 
```

**Comment by Po-Y-H** [comment]
I believe this is duplicate to #9.
