### ISSUE TITLE
Configure Github Actions for TDD

### ISSUE THREAD

**Issue by Po-Y-H** [CSCI-GA-2820-SP23-003/promotions#20]
**As a** Developer
**I need** to create a tdd.yml file and configure Github Actions
**So that** we can perform unit tests everytime we pull a request push to master
   
 ### Details and Assumptions
"Following TDD practices, place your test cases in a ./tests folder"

"Start developing by creating the TDD test_routes.py and test_models.py
files that contains your Unit Tests to test your service routes and your model 
respectively"

### Acceptance Criteria  
   
 ```gherkin
 Given developer pushes to master branch
 When the automated build fails
 Then abort the merge

 Given developer submit a PR
 When the automated build fails
 Then dont create PR

 Given developer pushes to master branch or submit a PR
 When the automated build passes
 Then respective actions are carried out successfully
```

**Comment by harshitakukreja** [comment]
Same as #72
