### ISSUE TITLE
Need the Ability to add a new promotion

### ISSUE THREAD

**Issue by soowhan-park** [CSCI-GA-2820-SP23-003/promotions#6]
**As a** Promotion Team Manager
**I need** the ability to create a new promotion   
**So that** I can provide special promotions/discounts to customers
   
 ### Details and Assumptions
We will store the following information in a PostgreSQL database: 
- product id (int) 
- customer id (int)
- Original Price (float)
- discount percentage(float) -> 0 if discounted by a fixed integer i.e. $5, $10 
- discount fixed amount(int)  -> 0 if discounted by percentage i.e. 10%
- Final price (float) 

   
 ### Acceptance Criteria  
   
 ```
 Given the service is running 
 When the manager adds a new discount on a product
 Then the new price needs to be updated in the database
```

**Comment by kk3039** [comment]
Should we also add information on promo expiration dates? E.g. eligible for two weeks after sign up, eligible from 12.25 - 12.31 etc

**Comment by soowhan-park** [comment]
> Should we also add information on promo expiration dates? E.g. eligible for two weeks after sign up, eligible from 12.25 - 12.31 etc

Good point, I'd suggest to create a new user story to design a schema of DB for Promotions.

**Comment by kk3039** [comment]
What are the types of promotions that we are going to support? So far, I am seeing:
-<product>, <% off>
-<product>, <$ off>
-site <% off>

**Comment by kk3039** [comment]
Original Price (float) and final price should be out of scope for us - these are within product team and cart team/ site UI scope

**Comment by soowhan-park** [comment]
> What are the types of promotions that we are going to support? So far, I am seeing:
> 
> * product, % off
> * product, $ off
> * site <% off>

I think we could also add [n] months of free promotions.

**Comment by kk3039** [comment]
>I think we could also add [n] months of free promotions.

I'll create a story on this as a topic to discuss tomorrow
