### ISSUE TITLE
Deploy the Promotion service to our Kubernetes Cluster

### ISSUE THREAD

**Issue by soowhan-park** [CSCI-GA-2820-SP23-003/promotions#68]
**As a** backend developer
**I need** to deploy the service to the cluster
**So that** the service runs in Kubernetes on IBM Cloud
   
 ### Details and Assumptions
 * Use the Kubernetes CLI _kubectl_ command to deploy the service
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that configurations are finished
 When the _kubectl_ command is executed
 Then our service is successfully deployed 
```

**Comment by harshitakukreja** [comment]
![Screenshot 2023-04-05 at 12.55.28 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/c70ad5a4-4147-473d-a380-0cbd4b421da6)![Screenshot 2023-04-05 at 12.55.44 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/2996bf8b-a0ad-4666-8560-28a107334a20)![Screenshot 2023-04-05 at 12.56.00 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/6faae594-6eec-41da-be2a-5e7c0ad53dde)![Screenshot 2023-04-05 at 12.56.33 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/b23d7dad-5ae7-4d19-90d2-0855a397baf2)![Screenshot 2023-04-05 at 12.57.17 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/5dfc0638-9c9a-461c-af85-ee35ea5d1f22)![Screenshot 2023-04-05 at 12.59.57 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/184f43b6-68eb-49b6-a290-2e944e45e1ad)
