### ISSUE TITLE
Add LIST promotion in UI page and BDD tests

### ISSUE THREAD

**Issue by Po-Y-H** [CSCI-GA-2820-SP23-003/promotions#78]
**As a** user
**I need** User Interface for LIST a promotion
**So that** I can easily sending requests., debugging and getting JSON 
   
 ### Details and Assumptions
 * write test cases for feature in BDD .feature and steps.py files
 * add a scenario in the feature file using Gherkin style

 ### Acceptance Criteria  
   
 ```gherkin
 Given the UI
 When enter the list request in input boxes
 Then all the Promotions is shown as such.
```

**Comment by soowhan-park** [comment]
I'm not sure if we need to add a separate button to display all the promotions. This is already done when you click "Search" without inputting anything
