### ISSUE TITLE
Add a Production Deploy stage to the Pipeline

### ISSUE THREAD

**Issue by soowhan-park** [CSCI-GA-2820-SP23-003/promotions#84]
**As a** Promotion Manager
**I need** the Production Deploy stage in the DevOps Continuous Delivery Pipeline
**So that** our project can automatically build and deploy when the master branch changes
   
 ### Details and Assumptions
 * Set up the DevOps Continuous Delivery Pipeline in IBM Cloud to build and deploy the project when the master branch changes.
 * Connect this DevOps pipeline to the GitHub repository for the project via a webhook.
 * Add a Production Deploy Stage to the pipeline to deploy to the `prod` namespace if all of the integration tests pass.   

 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running 
 When the master branch is updated 
 Then the build is automatically deployed to the prod namespace
```

**Comment by harshitakukreja** [comment]
![Screenshot 2023-05-03 at 2.09.55 AM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/d897e752-99cf-4d09-9f84-175187d6bb94)

**Comment by harshitakukreja** [comment]
![Screenshot 2023-05-03 at 5.04.26 PM.png](https://images.zenhubusercontent.com/63e539cdbffaf626d3b0f84a/19d7b090-47e1-4533-adf9-33ed2ca2401c)
